name: iOS starter workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: sparkfabrik/ios-build-action@v2.0.0
        with:
          upload-to-testflight: true
          increment-build-number: false
          build-pods: false
          configuration: Release
          export-method: app-store
          workspace-path: ${{ secrets.WORKSPACE_PATH }}
          project-path: ${{ secrets.PROJECT_PATH }}
          scheme: TbilisiCleanups
          output-path: build-${{ github.sha }}.ipa
          apple-key-id: ${{ secrets.APPLE_KEY_ID }}
          apple-key-issuer-id: ${{ secrets.APPLE_KEY_ISSUER_ID }}
          apple-key-content: ${{ secrets.APPLE_KEY_CONTENT }}
          team-id: ${{ secrets.TEAM_ID }}
          team-name: ${{ secrets.TEAM_NAME }}
          match-password: ${{ secrets.MATCH_PASSWORD }}
          match-git-url: ${{ secrets.MATCH_GIT_URL }}
          match-git-basic-authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          match-build-type: 'appstore'
          browserstack-upload: false
