name: Deploy to TestFlight

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Fastlane
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: bundle exec fastlane beta
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          git_basic_authorization: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
