name: PR Checks

on:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    name: PR Checks
    runs-on: macOS-12

    steps:
      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run:
          bundle exec danger --verbose

