name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:
  build:
    name: PR Checks
    runs-on: macOS-12

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run bundle install
        run:
          bundle install

      - name: Danger
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
        run:
          bundle exec danger --verbose

